package com.example.demo;

/***+
 * This class is used to format the error_message generated by the validation method by adding commas when
 * more than one fields are missing or null
 * @author apoudal
 */
public class StringFormatting {

    /***+
     * This method adds a comma to the error_message if more than one fields are missing or null using replace method replacing
     * a space with commma.
     * @param notFormmattedString
     * @return null1
     */
    public static StringBuilder stringFormat(StringBuilder notFormmattedString) {
        String null1= String.valueOf(notFormmattedString);
        null1=null1.trim().replace(" ",",");
        return new StringBuilder(null1);
    }
}
